name: Build & test

on:
  workflow_dispatch:
    inputs:
      var:
        description: "example variable 'var' with default value 'value'"
        required: false
        default: "value"
  push:
    branches:
      - '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📖 Checkout Code
        uses: actions/checkout@v4

      - name: 🎛️ Set environment
        run: |
          echo "GITHUB_SHA_SHORT=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: 🦀 Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1

      - name: rust cache
        uses: Swatinem/rust-cache@v2
        with:
          cache-on-failure: "true"
      
      - name: 📦 Install
        run: scripts/install.sh

      - name: 🛠️ Build Plugins
        run: scripts/build.sh
      
      - name: 🧰 Build Horizon
        run: |
          cd Horizon
          RUSTFLAGS="" cargo build --bin horizon --release
      
      - name: Update config of Horizon
        run: |
          sed -i 's/8081/7040/g' Horizon/config.toml
          sed -i 's/tick_interval_ms = 50/tick_interval_ms = 16/g' Horizon/config.toml
          sed -i 's/min_x = -1000.0/min_x = -10000000.0/g' Horizon/config.toml
          sed -i 's/max_x = 1000.0/max_x = 10000000.0/g' Horizon/config.toml
          sed -i 's/min_y = -1000.0/min_y = -10000000.0/g' Horizon/config.toml
          sed -i 's/max_y = 1000.0/max_y = 10000000.0/g' Horizon/config.toml
          sed -i 's/min_z = -100.0/min_z = -10000000.0/g' Horizon/config.toml
          sed -i 's/max_z = 100.0/max_z = 10000000.0/g' Horizon/config.toml

      - name: prepare tests
        run: |
          cd tests
          npm install

      - name: Start Horizon Server for Tests
        run: |
          cd Horizon
          nohup ./target/release/horizon &
          sleep 5

      - name: 🧪 Run Tests
        run: |
          cd tests
          npm test
